/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker\src\worker-configuration.d.ts` (hash: 8633c3129f6569229331ae51be0180b7)
interface __BaseEnv_WorkerEnv {
	DB: D1Database;
	APP_ENV: string;
	FRONTEND_URL: string;
	CORS_ORIGIN: string;
	BRANCH_NAME: string;
	SHOP_TIMEZONE: string;
	SHOP_OPEN_TIME: string;
	SHOP_CLOSE_TIME: string;
	SERVICE_DURATION_MINUTES: string;
	SLOT_INTERVAL_MINUTES: string;
	MAX_ONLINE_SEATS: string;
	MAX_BOOKINGS_PER_USER: string;
	MAX_ADVANCE_DAYS: string;
	ALLOW_SAME_DAY_BOOKING: string;
	ENABLE_DEV_AUTH: string;
	ADMIN_API_KEY: string;
	SESSION_SECRET: string;
	LINE_LOGIN_CHANNEL_ID: string;
	LINE_LOGIN_CHANNEL_SECRET: string;
	LINE_LOGIN_REDIRECT_URI: string;
	LINE_MESSAGING_CHANNEL_ACCESS_TOKEN: string;
	LINE_MESSAGING_CHANNEL_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "FRONTEND_URL" | "CORS_ORIGIN" | "BRANCH_NAME" | "SHOP_TIMEZONE" | "SHOP_OPEN_TIME" | "SHOP_CLOSE_TIME" | "SERVICE_DURATION_MINUTES" | "SLOT_INTERVAL_MINUTES" | "MAX_ONLINE_SEATS" | "MAX_BOOKINGS_PER_USER" | "MAX_ADVANCE_DAYS" | "ALLOW_SAME_DAY_BOOKING" | "ENABLE_DEV_AUTH" | "ADMIN_API_KEY" | "SESSION_SECRET" | "LINE_LOGIN_CHANNEL_ID" | "LINE_LOGIN_CHANNEL_SECRET" | "LINE_LOGIN_REDIRECT_URI" | "LINE_MESSAGING_CHANNEL_ACCESS_TOKEN" | "LINE_MESSAGING_CHANNEL_SECRET">> {}
}
